spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/retail_order_service}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:retail_order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:retail_order_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
